### ISSUE TITLE
소모임 가입 기능 추가

### ISSUE THREAD

**Issue by gyureal** [gyureal/weGather#26]
## TODO

- [x] 소모임 가입 기존 기능 제거
- [x] 소모임 가입 추가
   - [x] 소모임 `가입 요청`을 하고, 모임장이 `승인`하면 소모임에 가입할 수 있다.
   - [x] 한번 가입한 회원은 재가입할 수 없다.
   - [x] 소모임장이 `가입 요청`목록을 조회할 수 있다. 회원의 간략한 정보를 볼 수 있다.
   - [x] `승인` 또는 `거부`를 할 수 있다.

## API 명세
https://great-lizard-b83.notion.site/API-d1ca66eb2a554be68e47284d727a59e3?pvs=4
