### ISSUE TITLE
소모임 소개 수정 기능 개발

### ISSUE THREAD

**Issue by gyureal** [gyureal/weGather#46]
## 목적
소모임 정보를 수정하는 기능을 개발합니다.

## TODO
- [x] 짧은 소개, 상세 소개 수정
- [x] 썸네일 수정 기능 추가
- [x] 유효성 체크
   - [x] 소모임 관리자만 수정 가능
