### ISSUE TITLE
이미지 업로드 기능 리팩토링 (base64 -> multipart)

### ISSUE THREAD

**Issue by gyureal** [gyureal/weGather#50]
## 목적
> 이미지 업로드 기능을 base64 방식에서 multipart 방식으로 변환합니다. base64 방식은 서버에서 디코딩하는 작업이 필요하기 때문에 서버 리소스를 소비하고, 성능또한 저하되기 때문에 multipart 형식으로 변경합니다.

## TODO
- [x] 프로필 업로드 기능 수정
- [x] 소모임 배너 이미지 업로드 기능 수정
- [x] 소모임 썸네일 이미지 업로드 기능 수정
- [x] 이미지 업로드 용량 3MB로 제한
